version: "3.8"

services:
  zomboid-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GID: "${GID:?err}"
    restart: unless-stopped
    container_name: zomboid-server
    ports:
      # Default port for connecting
      - "16261:16261/udp"
      - "16261:16261/tcp"
      # Port range for player count (here 10 max)
      - "16262-16272:16262-16272/udp"
      - "16262-16272:16262-16272/tcp"
      # RCON port
      - "27015:27015/udp"
      - "27015:27015/tcp"
    environment:
      USER: "${USER:?err}"
      HOMEDIR: "${HOMEDIR:?err}"
      STEAMCMDDIR: "${STEAMCMDDIR:?err}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:?err}"
      SERVER_NAME: "${SERVER_NAME:?err}"
      PORT: "${PORT:?err}"
      UDP_PORT: "${UDP_PORT:?err}"
      STEAM_VAC: "${STEAM_VAC:?err}"
    volumes:
      # Contains everything about your server
      - ./server:/home/steam/Zomboid/
